name: Deploy FastAPI to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Setup
        run: |
          echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
          echo "SSH_AGENT_PID: $SSH_AGENT_PID"
          ssh-add -l
          echo "Testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

      - name: Copy files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/deploy_fastapi_test || mkdir ~/deploy_fastapi_test && cd ~/deploy_fastapi_test
            rm -rf ./*
          EOF
          scp -r ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deploy_fastapi_test

      - name: Deploy with Docker
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/deploy_fastapi_test
            
            # Stop and remove existing container
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            
            # Build new image
            docker build -t fastapi-app .
            
            # Check if port 80 is in use
            if lsof -i :80 > /dev/null; then
              echo "Port 80 is in use. Using port 8080 instead..."
              PORT=8080
            else
              PORT=80
            fi
            
            # Run the container
            docker run -d --name fastapi-app -p $PORT:8000 fastapi-app
            
            # Print the URL
            echo "Application is running on port $PORT"
            echo "You can access it at: http://$(hostname -I | awk '{print $1}'):$PORT"
          EOF
